### ISSUE TITLE
Provide Screenshots

### ISSUE THREAD

**Issue by ArchBlood** [cuzy-app/humhub-modules-cron-daemon#1]
Could you provide some screenshots showing examples of how the module can be set up, normally explaining it in the text can become confusing to the general user where screenshots provide a way of viewing the setup process and leads to less issues being created for common user setup issues.

Overall I like the module so far if any help is needed don't hesitate to ask 😄

**Comment by marc-farre** [comment]
Thanks @ArchBlood for the idea and the help proposal.
https://github.com/cuzy-app/humhub-modules-cron-daemon/releases/tag/1.0.3
