### ISSUE TITLE
Module does not work at all

### ISSUE THREAD

**Issue by Dschenns71** [cuzy-app/humhub-modules-cron-daemon#2]
I have installed the module. But after activation I go to configure and there it mentions 2 URLs which are not existent - and I only get a 404 Error message.

It seems, it does not read the HumHub Installation variable correct - besides some other issues...

**Comment by Dschenns71** [comment]
After the update, at least one of the CRON (queue) jobs work.
`<response>
<script/>
<code>200</code>
<message>Queue executed successfully!</message>
</response>`

But for the RUN I get this message:
`<response>
<script/>
<name>Internal Server Error</name>
<message>Es ist ein interner Serverfehler aufgetreten.</message>
<code>0</code>
<status>500</status>
</response>`

**Comment by marc-farre** [comment]
Sorry to have waited so long to answer you.
Fixed on version 1.0.2
https://github.com/cuzy-app/humhub-modules-cron-daemon/releases/tag/1.0.2

**Comment by Dschenns71** [comment]
Thank you very much!!!!
After so long time - you made my day :)
